First commits
cisagov/disable-inactive-iam-users-lambda pull request #1
Opened 2024-08-30 17:24 UTC by jsf9k

## 🗣 Description ##

This pull request implements the Python code for an AWS Lambda function that will disable users' inactive console and programmatic access.

## 💭 Motivation and context ##

The COOL has a POAM to disable inactive IAM users.

## 🧪 Testing ##

I applied this module to our COOL Users account without incident.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2024-08-30 19:41 UTC, dav3r approved these changes
Looks great!  I noted a few thangs in `validate_event_data` that I think you overlooked.

2024-08-30 19:41 UTC, dav3r commented on src/lambda_handler.py
> +        errors.append('"account_ids" must be non-null.')
Looks like you copy/pasted this from elsewhere, but didn't fully update it.  Is this what you meant?
```suggestion
    elif not event["expiration_days"]:
        errors.append('"expiration_days" must be non-null.')
```

2024-08-30 19:41 UTC, dav3r commented on src/lambda_handler.py
> +            errors.append('"account_ids" must be an integer.')
Fix copy/paste error:
```suggestion
            errors.append('"expiration_days" must be an integer.')
```

2024-08-30 19:41 UTC, dav3r commented on src/lambda_handler.py
> +                errors.append('"account_ids" must be a strictly positive integer.')
Fix copy/paste error:
```suggestion
                errors.append('"expiration_days" must be a strictly positive integer.')
```

2024-08-30 21:20 UTC, mcdonnnj requested changes
Please enable the dependabot ignore directives and fix the upstream repository reference in https://github.com/cisagov/disable-inactive-iam-users-lambda/blob/15fc27e20945f2a7a7945535c4a54647a6c1ce1f/.github/dependabot.yml#L22-L24

That reference changing suggests you have not updated your locally installed `skeleton` extension. Please update with `gh extension upgrade --all` to ensure you're working with the latest copy.

2024-09-02 17:30 UTC, jsf9k commented
> Please enable the dependabot ignore directives and fix the upstream repository reference in
> 
> https://github.com/cisagov/disable-inactive-iam-users-lambda/blob/15fc27e20945f2a7a7945535c4a54647a6c1ce1f/.github/dependabot.yml#L22-L24
> 
> That reference changing suggests you have not updated your locally installed `skeleton` extension. Please update with `gh extension upgrade --all` to ensure you're working with the latest copy.

Please see commit 469a51f.

2024-09-03 13:27 UTC, dv4harr10 commented
Hi Team, for README.md file section 'How to update Python dependencies' sentence 'More information about the Pipfile format can be found here.' The link from 'here' returns a 404 not found error.

2024-09-03 14:48 UTC, jsf9k commented
> Hi Team @ALL , for README.md file section 'How to update Python dependencies' sentence 'More information about the Pipfile format can be found here.' The link from 'here' returns a 404 not found error.

I created cisagov/skeleton-aws-lambda-python#32 to fix this upstream.

2024-09-03 16:16 UTC, dv4harr10 approved these changes

2024-09-05 18:02 UTC, jsf9k commented
@mcdonnnj - This work is due tomorrow, and you are out of the office, so I am going to assume that you are satisfied with the changes I made in response to your review.

2024-09-05 18:08 UTC, merged